kind: pipeline
type: exec
name: default
 
steps:
- name: build
  commands:
    - mkdir build
    - cd build
    - cmake cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release ../src
    - nice -n 19 make -j8
    - nice -n 19 make test
  when:
    branch:
      - master
      - c_api_approach
trigger:
event:
- push
- pull_request