os:
  - linux
language: cpp

services: docker

archlinux:
  packages:
    - cmake
    - boost
    - pango
    - adobe-source-code-pro-fonts
  mount:
    - ~/.pkg-cache:/var/cache/pacman/pkg
  before_install:
    - sudo sed -i '/#MAKEFLAGS=/c MAKEFLAGS="-j2"' /etc/makepkg.conf
  script:
    - mkdir build
    - cd build
    - cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=../testResult ../src
    - make -j2
    - ctest

cache:
    directories:
    - $HOME/AppData/Local/Temp/chocolatey
    - /C/tools/msys64
    - $HOME/.pkg-cache

script:
  - |-
    case $TRAVIS_OS_NAME in
      linux)
        curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash
        ;;
    esac
